# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31e3952a90708fb3c0e1d9aa22f43083a3247958c0724dbac89f389a48e420bbe523b50b4c4d5df8179b004b50e8e401f712821f2645bf77b65e70949a13f945

test:
  secret_key_base: cd0675d1651ba9f8c37e948a09663c3de5016421b3bbab252080b12229acf214ccab18e90f93731259c810672600e80f663172ada84ded3f4bc8590e15a4cfcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
